export const Users = [
  {
    id:1,
    profilePicture: "assets/img/persons/1.jpeg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "assets/img/persons/2.jpeg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "assets/img/persons/3.jpeg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/img/persons/4.jpeg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/img/persons/5.jpeg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "assets/img/persons/6.jpeg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/img/persons/7.jpeg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/img/persons/8.jpeg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/img/persons/9.jpeg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/img/persons/10.jpeg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/img/post/1.jpeg",
    date: "hace minutos 5",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "",
    photo: "assets/img/post/2.jpeg",
    date: "hace minutos 15",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/img/post/3.jpeg",
    date: "hace 1 hora",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "",
    photo: "assets/img/post/4.jpeg",
    date: "hace 4 horas",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "",
    photo: "assets/img/post/5.jpeg",
    date: "hace 5 horas",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    desc: "",
    photo: "assets/img/post/6.jpeg",
    date: "hace 1 día",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/img/post/7.jpeg",
    date: "hace 2 días",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "",
    photo: "assets/img/post/8.jpeg",
    date: "hace 3 días",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/img/post/9.jpeg",
    date: "hace 5 días",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "",
    photo: "assets/img/post/10.jpeg",
    date: "hace 1 semana",
    userId: 10,
    like: 104,
    comment: 12,
  },
];